### ISSUE TITLE
Navbar: make clickable

### ISSUE THREAD

**Issue by sohkai** [aragon/network-dashboard#37]
<img width="216" alt="Screen Shot 2020-08-27 at 6 26 46 PM" src="https://user-images.githubusercontent.com/4166642/91468904-ef8bb080-e892-11ea-8793-b9747fb6e1a0.png">

Small annoyance; usually these headers are clickable :). Not entirely sure where it would lead to you, but probably the proposals route?

I think it would also be ideal if the text was unselectable (this probably applies across the entire navbar and some other headers / etc in the app?)

**Comment by andy-hook** [comment]
Fixed in https://github.com/aragon/network-dashboard/pull/43
